import eslintJs from '@eslint/js'
import vitest from '@vitest/eslint-plugin'

export default [
  // 1. Default (all files): @eslint/js recommended rules + browser/node globals
  {
    ...eslintJs.configs.recommended,
    languageOptions: {
      globals: {
        ...eslintJs.configs.recommended.languageOptions?.globals ?? {},
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        performance: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        XMLHttpRequest: 'readonly',
        Event: 'readonly',
        ErrorEvent: 'readonly',
        CustomEvent: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        Promise: 'readonly',
        Set: 'readonly',
        Map: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        ArrayBuffer: 'readonly',
        DataView: 'readonly',
        Int8Array: 'readonly',
        Uint8Array: 'readonly',
        Uint8ClampedArray: 'readonly',
        Int16Array: 'readonly',
        Uint16Array: 'readonly',
        Int32Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        Float64Array: 'readonly',
        BigInt64Array: 'readonly',
        BigUint64Array: 'readonly',
        Atomics: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Reflect: 'readonly',
        Proxy: 'readonly',
        Symbol: 'readonly',
        Infinity: 'readonly',
        NaN: 'readonly',
        undefined: 'readonly',
        eval: 'readonly',
        globalThis: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __filename: 'readonly',
        __dirname: 'readonly',
        fetch: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        crypto.getRandomValues: 'readonly',
        structuredClone: 'readonly',
      },
    },
  },
  // 2. Tests (**/*.test.js): vitest plugin with recommended rules + specific rules
  {
    files: ['**/*.test.js'],
    ignores: [],
    ...vitest.configs.recommended,
    plugins: {
      vitest,
    },
    rules: {
      ...vitest.configs.recommended.rules,
      'vitest/expect-expect': ['error', { assertFunctionNames: ['expect', '**.expect'] }],
      'vitest/no-only-tests': 'error',
    },
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        describe: 'readonly',
        test: 'readonly',
        fit: 'readonly',
        xdescribe: 'readonly',
        xit: 'readonly',
        xtest: 'readonly',
      },
    },
  },
  // 3. Vitest config file: node globals only
  {
    files: ['vitest.config.js'],
    languageOptions: {
      globals: {
        ...vitest.environments.env?.globals,
      },
    },
  },
  // 4. Ignored paths: node_modules/, dist/, tests/e2e/
  {
    ignores: ['node_modules/', 'dist/', 'tests/e2e/'],
  },
]
